
module.exports = 
    
        {
            // January -----------------------------------------------------

            jan1:[{name:["LEELAMMA GEORGE"],place:["ARABI"]}],
            jan2:[{name:["VALSALA VINCENT"],place:["TALAP"]}],
            jan3:[{name:[],place:[]}],
            jan4:[{name:[],place:[]}],
            jan5:[{name:[],place:[]}],
            jan6:[{name:[],place:[]}],
            jan7:[{name:[],place:[]}],
            jan8:[{name:[],place:[]}],
            jan9:[{name:[],place:[]}],
            jan10:[{name:["MINI MATHEW"],place:["PARAKKAPPARA"]}],
            jan11:[{name:["DORIS LABAN"],place:["CHOVVA"]}],
            jan12:[{name:[],place:[]}],
            jan13:[{name:[],place:[]}],
            jan14:[{name:[],place:[]}],
            jan15:[{name:[],place:[]}],
            jan16:[{name:["ELIYAMMA THOMAS"],place:["ARABI"]}],
            jan17:[{name:[],place:[]}],
            jan18:[{name:['JEENA MANOJ'],place:["HEBICH'S KANNUR"]}],
            jan19:[{name:[],place:[]}],
            jan20:[{name:[],place:[]}],
            jan21:[{name:[],place:[]}],
            jan22:[{name:[],place:[]}],
            jan23:[{name:[],place:[]}],
            jan24:[{name:[],place:[]}],
            jan25:[{name:[],place:[]}],
            jan26:[{name:[],place:[]}],
            jan27:[{name:[],place:[]}],
            jan28:[{name:[],place:[]}],
            jan29:[{name:['SHYLA JOSEPH'],place:['KULAPPURAM']}],
            jan30:[{name:[],place:[]}],
            jan31:[{name:[],place:[]}],

            // February ---------------------------------------------------------------

            feb1:[{name:[],place:[]}],
            feb2:[{name:["LINTA RAJU CHEERAN"],place:["ST. JOHN'S KANNUR"]}],
            feb3:[{name:[],place:[]}],
            feb4:[{name:['JINYMOL E D '],place:['TALAP']}],
            feb5:[{name:[],place:[]}],
            feb6:[{name:[],place:[]}],
            feb7:[{name:["MANJU MANOHAR"],place:["CHOVVA"]}],
            feb8:[{name:[],place:[]}],
            feb9:[{name:[],place:[]}],
            feb10:[{name:[],place:[]}],
            feb11:[{name:[],place:[]}],
            feb12:[{name:["REMYA BINOY"],place:["KUTHUPARAMBU"]}],
            feb13:[{name:[],place:[]}],
            feb14:[{name:[],place:[]}],
            feb15:[{name:[],place:[]}],
            feb16:[{name:[],place:[]}],
            feb17:[{name:[],place:[]}],
            feb18:[{name:[],place:[]}],
            feb19:[{name:[],place:[]}],
            feb20:[{name:[],place:[]}],
            feb21:[{name:[],place:[]}],
            feb22:[{name:[],place:[]}],
            feb23:[{name:["SAVITHA BINOY"],place:["CHOVVA"]}],
            feb24:[{name:[],place:[]}],
            feb25:[{name:[],place:[]}],
            feb26:[{name:[],place:[]}],
            feb27:[{name:["SHEENA SUMAN"],place:["CHOVVA"]}],
            feb28:[{name:['CHRISTINA SUJITH'],place:['ALAKKOD']}],
            feb29:[{name:[],place:[]}],

            // March  ------------------------------------------------------------

            mar1:[{name:[],place:[]}],
            mar2:[{name:[],place:[]}],
            mar3:[{name:[],place:[]}],
            mar4:[{name:[],place:[]}],
            mar5:[{name:['JESNA SHIJU'],place:['CHOOTTAD']}],
            mar6:[{name:[],place:[]}],
            mar7:[{name:[],place:[]}],
            mar8:[{name:[],place:[]}],
            mar9:[{name:[],place:[]}],
            mar10:[{name:[],place:[]}],
            mar11:[{name:['SUBA SHAMJITH'],place:["ST.JOHN'S KANNUR"]}],
            mar12:[{name:['DIVYA DELNA K ','NISHA JOY'],place:['TALAP','ANAPANTHI']}],
            mar13:[{name:[],place:[]}],
            mar14:[{name:[],place:[]}],
            mar15:[{name:["MINI MATHEW"],place:["IRITTY"]}],
            mar16:[{name:[],place:[]}],
            mar17:[{name:["REENU ADORN"],place:["CHOVVA"]}],
            mar18:[{name:[],place:[]}],
            mar19:[{name:['LAVANYA BION'],place:['THALASSERY']}],
            mar20:[{name:[],place:[]}],
            mar21:[{name:['SALILA FISTRON'],place:['CHOOTTAD']}],
            mar22:[{name:[],place:[]}],
            mar23:[{name:[],place:[]}],
            mar24:[{name:["PRAVEENA JOY"],place:["TALAP"]}],
            mar25:[{name:[],place:[]}],
            mar26:[{name:[],place:[]}],
            mar27:[{name:[],place:[]}],
            mar28:[{name:[],place:[]}],
            mar29:[{name:[],place:[]}],
            mar30:[{name:[],place:[]}],
            mar31:[{name:[],place:[]}],

            // April -----------------------------------------------------------------------

            apr1:[{name:[],place:[]}],
            apr2:[{name:[],place:[]}],
            apr3:[{name:['RINATA ANGEL LIVINGSTON'],place:['CHOMBALA']}],
            apr4:[{name:[],place:[]}],
            apr5:[{name:['SABITHA PRASANTH'],place:['PAYYANNUR']}],
            apr6:[{name:[],place:[]}],
            apr7:[{name:[],place:[]}],
            apr8:[{name:[],place:[]}],
            apr9:[{name:['NIRMAL MONDODY'],place:['THALASSERY']}],
            apr10:[{name:["VALSAMMA GEORGE"],place:["KULAPPURAM"]}],
            apr11:[{name:[],place:[]}],
            apr12:[{name:['USHA'],place:['THALASSERY']}],
            apr13:[{name:[],place:[]}],
            apr14:[{name:[],place:[]}],
            apr15:[{name:["LITTY DANIEL"],place:["CHOVVA"]}],
            apr16:[{name:[],place:[]}],
            apr17:[{name:[],place:[]}],
            apr18:[{name:['PREMA BAI JAMES'],place:['THALASSERY']}],
            apr19:[{name:[],place:[]}],
            apr20:[{name:["LALI MATHEW"],place:["MATTUL"]}],
            apr21:[{name:[],place:[]}],
            apr22:[{name:["SHOBHA VALSAN"],place:["THALASSERY"]}],
            apr23:[{name:[],place:[]}],
            apr24:[{name:[],place:[]}],
            apr25:[{name:[],place:[]}],
            apr26:[{name:[],place:[]}],
            apr27:[{name:["SHEEBA JOHNSON","NISHA JAISON"],place:["NEDUVALOOR","PAPPINISSERY"]}],
            apr28:[{name:[],place:[]}],
            apr29:[{name:["VALSA PATHROS"],place:["NEDUVALOOR"]}],
            apr30:[{name:[],place:[]}],

            // May ----------------------------------------------------------------

            may1:[{name:[],place:[]}],
            may2:[{name:[],place:[]}],
            may3:[{name:["WILMA NATHAN"],place:["CHOVVA"]}],
            may4:[{name:[],place:[]}],
            may5:[{name:[],place:[]}],
            may6:[{name:[],place:[]}],
            may7:[{name:[],place:[]}],
            may8:[{name:[],place:[]}],
            may9:[{name:[],place:[]}],
            may10:[{name:[],place:[]}],
            may11:[{name:[],place:[]}],
            may12:[{name:[],place:[]}],
            may13:[{name:[],place:[]}],
            may14:[{name:["ANNE TREVOR"],place:["CHOVVA"]}],
            may15:[{name:["SHEEJA MERLIN"],place:["HEBICH'S KANNUR"]}],
            may16:[{name:[],place:[]}],
            may17:[{name:["JESSY LINET RIJOY"],place:["VADAKARA"]}],
            may18:[{name:["NEENA SAMSON"],place:["PAPPINISSERY"]}],
            may19:[{name:[],place:[]}],
            may20:[{name:["NINA SANTHOSH",'ANNAMMA FEDRIC'],place:["CHOVVA",'PAYYANNUR']}],
            may21:[{name:["MINI HERMON"],place:["NETTUR"]}],
            may22:[{name:[],place:[]}],
            may23:[{name:["SANDHYA PRAPHUL"],place:["CHOVVA"]}],
            may24:[{name:[],place:[]}],
            may25:[{name:[],place:[]}],
            may26:[{name:[],place:[]}],
            may27:[{name:[],place:[]}],
            may28:[{name:[],place:[]}],
            may29:[{name:[],place:[]}],
            may30:[{name:["OMANA","SIJI PYARILAL"],place:["ARABI","CHOVVA"]}],
            may31:[{name:["RAJEENA PRASANNA SUNIL",'KRISTEENA T K','ANNAMMA CHRISPUS'],place:["CHOVVA",'PADIYOOR','CHOOTTAD']}],

            // June ---------------------------------------------------------

            jun1:[{name:["PADMINI CHANDRAKANTH"],place:["CHOMBALA"]}],
            jun2:[{name:['REENA BRIJESH'],place:['CHOOTTAD']}],
            jun3:[{name:[],place:[]}],
            jun4:[{name:[],place:[]}],
            jun5:[{name:[],place:[]}],
            jun6:[{name:[],place:[]}],
            jun7:[{name:[],place:[]}],
            jun8:[{name:[],place:[]}],
            jun9:[{name:[],place:[]}],
            jun10:[{name:["ROYSALINE MRIDULA"],place:["CHOVVA"]}],
            jun11:[{name:[],place:[]}],
            jun12:[{name:[],place:[]}],
            jun13:[{name:[],place:[]}],
            jun14:[{name:[],place:[]}],
            jun15:[{name:["ELIAMMA KENNET",'JESSY RAJU'],place:["CHOVVA",'VADAKARA-MOORAD']}],
            jun16:[{name:[],place:[]}],
            jun17:[{name:["JISHA JOSEPH",'SHIBI VINOD'],place:["PAPPINISSERY",'PAYYANNUR']}],
            jun18:[{name:[],place:[]}],
            jun19:[{name:[],place:[]}],
            jun20:[{name:[],place:[]}],
            jun21:[{name:[],place:[]}],
            jun22:[{name:["SHEEBA SUNIL"],place:["HEBICH'S KANNUR"]}],
            jun23:[{name:[],place:[]}],
            jun24:[{name:[],place:[]}],
            jun25:[{name:[],place:[]}],
            jun26:[{name:[],place:[]}],
            jun27:[{name:[],place:[]}],
            jun28:[{name:[],place:[]}],
            jun29:[{name:[],place:[]}],
            jun30:[{name:[],place:[]}],

            // July -----------------------------------------------------------------------

            july1:[{name:[],place:[]}],
            july2:[{name:[],place:[]}],
            july3:[{name:["MEENA RAJAN"],place:["PAPPINISSEY"]}],
            july4:[{name:[],place:[]}],
            july5:[{name:[],place:[]}],
            july6:[{name:[],place:[]}],
            july7:[{name:["SAJITHA MARIAM PHILIP","SHYMA DANIEL"],place:["MADAYI","CHOVVA"]}],
            july8:[{name:[],place:[]}],
            july9:[{name:[],place:[]}],
            july10:[{name:['MARY JOHN'],place:['TALAP']}],
            july11:[{name:[],place:[]}],
            july12:[{name:[],place:[]}],
            july13:[{name:[],place:[]}],
            july14:[{name:["LIJI SAM"],place:["PARAKKAPPARA-PADIYOOR"]}],
            july15:[{name:[],place:[]}],
            july16:[{name:[],place:[]}],
            july17:[{name:["MINI SURESH"],place:["MADAYI"]}],
            july18:[{name:[],place:[]}],
            july19:[{name:[],place:[]}],
            july20:[{name:['BEENA'],place:['THALASSERY']}],
            july21:[{name:[],place:[]}],
            july22:[{name:["LUCY PREMALATHA"],place:["ST. JOHN'S KANNUR"]}],
            july23:[{name:["GLADYS WILLIAM"],place:["HEBICH'S KANNUR"]}],
            july24:[{name:[],place:[]}],
            july25:[{name:[],place:[]}],
            july26:[{name:[],place:[]}],
            july27:[{name:[],place:[]}],
            july28:[{name:[],place:[]}],
            july29:[{name:["RAJI SUJIN"],place:["CHOVVA"]}],
            july30:[{name:[],place:[]}],
            july31:[{name:[],place:[]}],

            // August --------------------------------------------------------

            aug1:[{name:[],place:[]}],
            aug2:[{name:[],place:[]}],
            aug3:[{name:[],place:[]}],
            aug4:[{name:[],place:[]}],
            aug5:[{name:["SHARMILA SAMUEL"],place:["CHOVVA"]}],
            aug6:[{name:[],place:[]}],
            aug7:[{name:[],place:[]}],
            aug8:[{name:["NEETHU JIJO"],place:["NETTUR"]}],
            aug9:[{name:[],place:[]}],
            aug10:[{name:['JESSY WINSTON'],place:['PAYYANNUR']}],
            aug11:[{name:["BHANUMATHI JAYAPRAKASH"],place:["TALAP"]}],
            aug12:[{name:[],place:[]}],
            aug13:[{name:[],place:[]}],
            aug14:[{name:[],place:[]}],
            aug15:[{name:[],place:[]}],
            aug16:[{name:[],place:[]}],
            aug17:[{name:[],place:[]}],
            aug18:[{name:[],place:[]}],
            aug19:[{name:['PERLY MANOHAR'],place:['THALASSERY']}],
            aug20:[{name:[],place:[]}],
            aug21:[{name:[],place:[]}],
            aug22:[{name:[],place:[]}],
            aug23:[{name:[],place:[]}],
            aug24:[{name:["MABLE MOHAN"],place:["CHOVVA"]}],
            aug25:[{name:["ELSY SHOBHA HUTTON"],place:["CHOVVA"]}],
            aug26:[{name:["ANILA LIVINGSTON"],place:["CHOVVA"]}],
            aug27:[{name:[],place:[]}],
            aug28:[{name:['BABITHA KENNET'],place:["HEBICH'S KANNUR"]}],
            aug29:[{name:[],place:[]}],
            aug30:[{name:[],place:[]}],
            aug31:[{name:[],place:[]}],

            // September ------------------------------------------------------------

            sep1:[{name:[],place:[]}],
            sep2:[{name:[],place:[]}],
            sep3:[{name:[],place:[]}],
            sep4:[{name:[],place:[]}],
            sep5:[{name:[],place:[]}],
            sep6:[{name:[],place:[]}],
            sep7:[{name:["LIZ JOSEPHINE GEORGE"],place:["CHOMBALA"]}],
            sep8:[{name:['ANITHA'],place:['THALASSERY']}],
            sep9:[{name:[],place:[]}],
            sep10:[{name:[],place:[]}],
            sep11:[{name:[],place:[]}],
            sep12:[{name:[],place:[]}],
            sep13:[{name:[],place:[]}],
            sep14:[{name:["SHIRLY SHAJI","JASMINE SHYNA SOLOMON"],place:["CHOVVA","HEBICH'S KANNUR"]}],
            sep15:[{name:[],place:[]}],
            sep16:[{name:[],place:[]}],
            sep17:[{name:["BEENA MANMOHAN",'OMANA JAMES'],place:["CHOVVA",'KULAPPURAM']}],
            sep18:[{name:[],place:[]}],
            sep19:[{name:[],place:[]}],
            sep20:[{name:["MERLIN SAROJINI"],place:["HEBICH'S KANNUR"]}],
            sep21:[{name:[],place:[]}],
            sep22:[{name:["MEERA JOSEPH"],place:["PAPPINISSERI"]}],
            sep23:[{name:["JINTO SHAJAN"],place:["ARABI"]}],
            sep24:[{name:[],place:[]}],
            sep25:[{name:[],place:[]}],
            sep26:[{name:['MERLIN JIJESH','MERLIN MATHEW'],place:['CHOOTTAD','CHOOTTAD']}],
            sep27:[{name:[],place:[]}],
            sep28:[{name:[],place:[]}],
            sep29:[{name:["SHEELA SAMUEL"],place:["CHOMBALA"]}],
            sep30:[{name:["BINANCY JOSE",'SMITHA JAMES'],place:["IRITTY-VALLITHODE",'ARABI']}],
            sep31:[{name:[],place:[]}],

            // October ------------------------------------------------------------

            oct1:[{name:[],place:[]}],
            oct2:[{name:[],place:[]}],
            oct3:[{name:[],place:[]}],
            oct4:[{name:["NIMINA MURIEL S"],place:["HEBICH'S KANNUR"]}],
            oct5:[{name:["SALLY DARREL"],place:["HEBICH'S KANNUR"]}],
            oct6:[{name:[],place:[]}],
            oct7:[{name:['PRIYA JISHWANTH'],place:["HEBICH'S KANNUR"]}],
            oct8:[{name:[],place:[]}],
            oct9:[{name:[],place:[]}],
            oct10:[{name:[],place:[]}],
            oct11:[{name:["ROSAMMA HUTTON"],place:["CHOVVA"]}],
            oct12:[{name:[],place:[]}],
            oct13:[{name:[],place:[]}],
            oct14:[{name:[],place:[]}],
            oct15:[{name:[],place:[]}],
            oct16:[{name:[],place:[]}],
            oct17:[{name:[],place:[]}],
            oct18:[{name:[],place:[]}],
            oct19:[{name:[],place:[]}],
            oct20:[{name:[],place:[]}],
            oct21:[{name:["LAILA SHERIL"],place:["CHOVVA"]}],
            oct22:[{name:["SHYAMA SIMON"],place:["HEBICH'S KANNUR"]}],
            oct23:[{name:[],place:[]}],
            oct24:[{name:[],place:[]}],
            oct25:[{name:["SARA KISHORE"],place:["HEBICH'S KANNUR"]}],
            oct26:[{name:[],place:[]}],
            oct27:[{name:["SREEJA SREEJESH","LIJI SHEENA PETER"],place:["KUTHUPARAMBA","CHOVVA"]}],
            oct28:[{name:[],place:[]}],
            oct29:[{name:[],place:[]}],
            oct30:[{name:[],place:[]}],
            oct31:[{name:[],place:[]}],

            // November ---------------------------------------------------

            nov1:[{name:[],place:[]}],
            nov2:[{name:["MINI RAJU"],place:["NEDUVALOOR"]}],
            nov3:[{name:["DILNA NELSON","RABEENA CHRISTABLE"],place:["CHOVVA","CHOVVA"]}],
            nov4:[{name:[],place:[]}],
            nov5:[{name:[],place:[]}],
            nov6:[{name:[],place:[]}],
            nov7:[{name:[],place:[]}],
            nov8:[{name:[],place:[]}],
            nov9:[{name:[],place:[]}],
            nov10:[{name:[],place:[]}],
            nov11:[{name:[],place:[]}],
            nov12:[{name:[],place:[]}],
            nov13:[{name:["TEENA JOANNE TREVOR"],place:["CHOVVA"]}],
            nov14:[{name:["LEELAMMA THOMAS"],place:["ANAPANTHI"]}],
            nov15:[{name:["VINEETHA ANDROS"],place:["PAYYANNUR"]}],
            nov16:[{name:[],place:[]}],
            nov17:[{name:[],place:[]}],
            nov18:[{name:["JINCY VARGHESE"],place:["ST. JOHN'S KANNUR"]}],
            nov19:[{name:[],place:[]}],
            nov20:[{name:[],place:[]}],
            nov21:[{name:[],place:[]}],
            nov22:[{name:['JESSY BABU'],place:['IRITTY VALLITHOD']}],
            nov23:[{name:['ANITHA NATHAN'],place:['TALAP']}],
            nov24:[{name:["REENA SHIRLY","MERLIN GEORGE"],place:["KULAPPURAM","CHOVVA"]}],
            nov25:[{name:[],place:[]}],
            nov26:[{name:[],place:[]}],
            nov27:[{name:[],place:[]}],
            nov28:[{name:[],place:[]}],
            nov29:[{name:[],place:[]}],
            nov30:[{name:[],place:[]}],
            nov31:[{name:[],place:[]}],

            // December ------------------------------------------------------------------

            dec1:[{name:["SHEELA ROSAJAN"],place:["CHOVVA"]}],
            dec2:[{name:[],place:[]}],
            dec3:[{name:[],place:[]}],
            dec4:[{name:["SHINY CHACKO","JANET SOUDAMINI"],place:["PARAKKAPPARA","MADAYI"]}],
            dec5:[{name:[],place:[]}],
            dec6:[{name:["TINTU SHAJI"],place:["NEDUVALOOR"]}],
            dec7:[{name:["BEENA PETER"],place:["ARABI"]}],
            dec8:[{name:[],place:[]}],
            dec9:[{name:[],place:[]}],
            dec10:[{name:[],place:[]}],
            dec11:[{name:[],place:[]}],
            dec12:[{name:[],place:[]}],
            dec13:[{name:["SUJATHA VINOD"],place:["MADAYI"]}],
            dec14:[{name:[],place:[]}],
            dec15:[{name:[],place:[]}],
            dec16:[{name:["SHINI ANIL"],place:["MATTUL"]}],
            dec17:[{name:[],place:[]}],
            dec18:[{name:[],place:[]}],
            dec19:[{name:[],place:[]}],
            dec20:[{name:[],place:[]}],
            dec21:[{name:[],place:[]}],
            dec22:[{name:[],place:[]}],
            dec23:[{name:["SHOBANA PETER"],place:["HEBICH'S KANNUR"]}],
            dec24:[{name:["LISSY ROBERT"],place:["ARABI"]}],
            dec25:[{name:["SHYMA VALSAKUMAR","MARY THOMAS","GRACY SAMUEL"],place:["CHOVVA","ARABI","ARABI"]}],
            dec26:[{name:[],place:[]}],
            dec27:[{name:["BINCY REJI"],place:["IRITTY VALLITHOD"]}],
            dec28:[{name:["JYOTHI ROMEO","SHUBA KARTHIK","NEETHU RENNY"],place:["MADAYI",'PAYYANNUR','MOORAD']}],
            dec29:[{name:[],place:[]}],
            dec30:[{name:[],place:[]}],
            dec31:[{name:[],place:[]}],
        }



