
module.exports = 
    
        {
            // January -----------------------------------------------------

            jan1:[{name:[],place:[]}],
            jan2:[{name:[],place:[]}],
            jan3:[{name:[],place:[]}],
            jan4:[{name:[],place:[]}],
            jan5:[{name:[],place:[]}],
            jan6:[{name:[],place:[]}],
            jan7:[{name:[],place:[]}],
            jan8:[{name:[],place:[]}],
            jan9:[{name:[],place:[]}],
            jan10:[{name:["MINI MATHEW"],place:["PARAKKAPPARA"]}],
            jan11:[{name:[],place:[]}],
            jan12:[{name:[],place:[]}],
            jan13:[{name:[],place:[]}],
            jan14:[{name:[],place:[]}],
            jan15:[{name:[],place:[]}],
            jan16:[{name:[],place:[]}],
            jan17:[{name:[],place:[]}],
            jan18:[{name:[],place:[]}],
            jan19:[{name:[],place:[]}],
            jan20:[{name:[],place:[]}],
            jan21:[{name:[],place:[]}],
            jan22:[{name:[],place:[]}],
            jan23:[{name:[],place:[]}],
            jan24:[{name:[],place:[]}],
            jan25:[{name:[],place:[]}],
            jan26:[{name:[],place:[]}],
            jan27:[{name:[],place:[]}],
            jan28:[{name:[],place:[]}],
            jan29:[{name:[],place:[]}],
            jan30:[{name:[],place:[]}],
            jan31:[{name:[],place:[]}],

            // February ---------------------------------------------------------------

            feb1:[{name:[],place:[]}],
            feb2:[{name:["LINTA RAJU CHEERAN"],place:["ST. JOHN'S KANNUR"]}],
            feb3:[{name:[],place:[]}],
            feb4:[{name:[],place:[]}],
            feb5:[{name:[],place:[]}],
            feb6:[{name:[],place:[]}],
            feb7:[{name:[],place:[]}],
            feb8:[{name:[],place:[]}],
            feb9:[{name:[],place:[]}],
            feb10:[{name:[],place:[]}],
            feb11:[{name:[],place:[]}],
            feb12:[{name:["REMYA BINOY"],place:["KUTHUPARAMBU"]}],
            feb13:[{name:[],place:[]}],
            feb14:[{name:[],place:[]}],
            feb15:[{name:[],place:[]}],
            feb16:[{name:[],place:[]}],
            feb17:[{name:[],place:[]}],
            feb18:[{name:[],place:[]}],
            feb19:[{name:[],place:[]}],
            feb20:[{name:[],place:[]}],
            feb21:[{name:[],place:[]}],
            feb22:[{name:[],place:[]}],
            feb23:[{name:[],place:[]}],
            feb24:[{name:[],place:[]}],
            feb25:[{name:[],place:[]}],
            feb26:[{name:[],place:[]}],
            feb27:[{name:[],place:[]}],
            feb28:[{name:[],place:[]}],
            feb29:[{name:[],place:[]}],

            // March  ------------------------------------------------------------

            mar1:[{name:[],place:[]}],
            mar2:[{name:[],place:[]}],
            mar3:[{name:[],place:[]}],
            mar4:[{name:[],place:[]}],
            mar5:[{name:[],place:[]}],
            mar6:[{name:[],place:[]}],
            mar7:[{name:[],place:[]}],
            mar8:[{name:[],place:[]}],
            mar9:[{name:[],place:[]}],
            mar10:[{name:[],place:[]}],
            mar11:[{name:[],place:[]}],
            mar12:[{name:[],place:[]}],
            mar13:[{name:[],place:[]}],
            mar14:[{name:[],place:[]}],
            mar15:[{name:["MINI MATHEW"],place:["IRITTY"]}],
            mar16:[{name:[],place:[]}],
            mar17:[{name:[],place:[]}],
            mar18:[{name:[],place:[]}],
            mar19:[{name:[],place:[]}],
            mar20:[{name:[],place:[]}],
            mar21:[{name:[],place:[]}],
            mar22:[{name:[],place:[]}],
            mar23:[{name:[],place:[]}],
            mar24:[{name:["PRAVEENA JOY"],place:["TALAP"]}],
            mar25:[{name:[],place:[]}],
            mar26:[{name:[],place:[]}],
            mar27:[{name:[],place:[]}],
            mar28:[{name:[],place:[]}],
            mar29:[{name:[],place:[]}],
            mar30:[{name:[],place:[]}],
            mar31:[{name:[],place:[]}],

            // April -----------------------------------------------------------------------

            apr1:[{name:[],place:[]}],
            apr2:[{name:[],place:[]}],
            apr3:[{name:[],place:[]}],
            apr4:[{name:[],place:[]}],
            apr5:[{name:[],place:[]}],
            apr6:[{name:[],place:[]}],
            apr7:[{name:[],place:[]}],
            apr8:[{name:[],place:[]}],
            apr9:[{name:[],place:[]}],
            apr10:[{name:["VALSAMMA GEORGE"],place:["KULAPPURAM"]}],
            apr11:[{name:[],place:[]}],
            apr12:[{name:[],place:[]}],
            apr13:[{name:[],place:[]}],
            apr14:[{name:[],place:[]}],
            apr15:[{name:[],place:[]}],
            apr16:[{name:[],place:[]}],
            apr17:[{name:[],place:[]}],
            apr18:[{name:[],place:[]}],
            apr19:[{name:[],place:[]}],
            apr20:[{name:["LALI MATHEW","hee","hlioyr"],place:["MATTUL","kozhikode","wayanad"]}],
            apr21:[{name:[],place:[]}],
            apr22:[{name:[],place:[]}],
            apr23:[{name:[],place:[]}],
            apr24:[{name:["SHOBHA VALSAN"],place:["THALASSERY"]}],
            apr25:[{name:[],place:[]}],
            apr26:[{name:[],place:[]}],
            apr27:[{name:["SHEEBA JOHNSON","NISHA JAISON"],place:["NEDUVALOOR","PAPPINISSERY"]}],
            apr28:[{name:[],place:[]}],
            apr29:[{name:["VALSA PATHROS"],place:["NEDUVALOOR"]}],
            apr30:[{name:[],place:[]}],

            // May ----------------------------------------------------------------

            may1:[{name:[],place:[]}],
            may2:[{name:[],place:[]}],
            may3:[{name:[],place:[]}],
            may4:[{name:[],place:[]}],
            may5:[{name:[],place:[]}],
            may6:[{name:[],place:[]}],
            may7:[{name:[],place:[]}],
            may8:[{name:[],place:[]}],
            may9:[{name:[],place:[]}],
            may10:[{name:[],place:[]}],
            may11:[{name:[],place:[]}],
            may12:[{name:[],place:[]}],
            may13:[{name:[],place:[]}],
            may14:[{name:[],place:[]}],
            may15:[{name:[],place:[]}],
            may16:[{name:[],place:[]}],
            may17:[{name:[],place:[]}],
            may18:[{name:[],place:[]}],
            may19:[{name:[],place:[]}],
            may20:[{name:[],place:[]}],
            may21:[{name:["MINI HERMON"],place:["NETTUR"]}],
            may22:[{name:[],place:[]}],
            may23:[{name:[],place:[]}],
            may24:[{name:[],place:[]}],
            may25:[{name:[],place:[]}],
            may26:[{name:[],place:[]}],
            may27:[{name:[],place:[]}],
            may28:[{name:[],place:[]}],
            may29:[{name:[],place:[]}],
            may30:[{name:[],place:[]}],
            may31:[{name:[],place:[]}],

            // June ---------------------------------------------------------

            jun1:[{name:[],place:[]}],
            jun2:[{name:[],place:[]}],
            jun3:[{name:[],place:[]}],
            jun4:[{name:[],place:[]}],
            jun5:[{name:[],place:[]}],
            jun6:[{name:[],place:[]}],
            jun7:[{name:[],place:[]}],
            jun8:[{name:[],place:[]}],
            jun9:[{name:[],place:[]}],
            jun10:[{name:[],place:[]}],
            jun11:[{name:[],place:[]}],
            jun12:[{name:[],place:[]}],
            jun13:[{name:[],place:[]}],
            jun14:[{name:[],place:[]}],
            jun15:[{name:[],place:[]}],
            jun16:[{name:[],place:[]}],
            jun17:[{name:["JISHA JOSEPH"],place:["PAPPINISSERY"]}],
            jun18:[{name:[],place:[]}],
            jun19:[{name:[],place:[]}],
            jun20:[{name:[],place:[]}],
            jun21:[{name:[],place:[]}],
            jun22:[{name:["SHEEBA SUNIL"],place:["HEBICH'S KANNUR"]}],
            jun23:[{name:[],place:[]}],
            jun24:[{name:[],place:[]}],
            jun25:[{name:[],place:[]}],
            jun26:[{name:[],place:[]}],
            jun27:[{name:[],place:[]}],
            jun28:[{name:[],place:[]}],
            jun29:[{name:[],place:[]}],
            jun30:[{name:[],place:[]}],

            // July -----------------------------------------------------------------------

            july1:[{name:[],place:[]}],
            july2:[{name:[],place:[]}],
            july3:[{name:["MEENA RAJAN"],place:["PAPPINISSEY"]}],
            july4:[{name:[],place:[]}],
            july5:[{name:[],place:[]}],
            july6:[{name:[],place:[]}],
            july7:[{name:["SAJITHA MARIAM PHILIP"],place:["MADAYI"]}],
            july8:[{name:[],place:[]}],
            july9:[{name:[],place:[]}],
            july10:[{name:[],place:[]}],
            july11:[{name:[],place:[]}],
            july12:[{name:[],place:[]}],
            july13:[{name:[],place:[]}],
            july14:[{name:[],place:[]}],
            july15:[{name:[],place:[]}],
            july16:[{name:[],place:[]}],
            july17:[{name:["MINI SURESH","LIJI SAM"],place:["MADAYI","PARAKKAPPARA"]}],
            july18:[{name:[],place:[]}],
            july19:[{name:[],place:[]}],
            july20:[{name:[],place:[]}],
            july21:[{name:[],place:[]}],
            july22:[{name:["LUCY PREMALATHA"],place:["ST. JOHN'S KANNUR"]}],
            july23:[{name:[],place:[]}],
            july24:[{name:[],place:[]}],
            july25:[{name:[],place:[]}],
            july26:[{name:[],place:[]}],
            july27:[{name:[],place:[]}],
            july28:[{name:[],place:[]}],
            july29:[{name:[],place:[]}],
            july30:[{name:[],place:[]}],
            july31:[{name:[],place:[]}],

            // August --------------------------------------------------------

            aug1:[{name:[],place:[]}],
            aug2:[{name:[],place:[]}],
            aug3:[{name:[],place:[]}],
            aug4:[{name:[],place:[]}],
            aug5:[{name:[],place:[]}],
            aug6:[{name:[],place:[]}],
            aug7:[{name:[],place:[]}],
            aug8:[{name:["NEETHU JIJO"],place:["NETTUR"]}],
            aug9:[{name:[],place:[]}],
            aug10:[{name:[],place:[]}],
            aug11:[{name:["BHANUMATHI JAYAPRAKASH"],place:["TALAP"]}],
            aug12:[{name:[],place:[]}],
            aug13:[{name:[],place:[]}],
            aug14:[{name:[],place:[]}],
            aug15:[{name:[],place:[]}],
            aug16:[{name:[],place:[]}],
            aug17:[{name:[],place:[]}],
            aug18:[{name:[],place:[]}],
            aug19:[{name:[],place:[]}],
            aug20:[{name:[],place:[]}],
            aug21:[{name:[],place:[]}],
            aug22:[{name:[],place:[]}],
            aug23:[{name:[],place:[]}],
            aug24:[{name:[],place:[]}],
            aug25:[{name:[],place:[]}],
            aug26:[{name:[],place:[]}],
            aug27:[{name:[],place:[]}],
            aug28:[{name:[],place:[]}],
            aug29:[{name:[],place:[]}],
            aug30:[{name:[],place:[]}],
            aug31:[{name:[],place:[]}],

            // September ------------------------------------------------------------

            sep1:[{name:[],place:[]}],
            sep2:[{name:[],place:[]}],
            sep3:[{name:[],place:[]}],
            sep4:[{name:[],place:[]}],
            sep5:[{name:[],place:[]}],
            sep6:[{name:[],place:[]}],
            sep7:[{name:["LIZ JOSEPHINE GEORGE"],place:["CHOMBALA"]}],
            sep8:[{name:[],place:[]}],
            sep9:[{name:[],place:[]}],
            sep10:[{name:[],place:[]}],
            sep11:[{name:[],place:[]}],
            sep12:[{name:[],place:[]}],
            sep13:[{name:[],place:[]}],
            sep14:[{name:[],place:[]}],
            sep15:[{name:[],place:[]}],
            sep16:[{name:[],place:[]}],
            sep17:[{name:[],place:[]}],
            sep18:[{name:[],place:[]}],
            sep19:[{name:[],place:[]}],
            sep20:[{name:[],place:[]}],
            sep21:[{name:[],place:[]}],
            sep22:[{name:[],place:[]}],
            sep23:[{name:[],place:[]}],
            sep24:[{name:[],place:[]}],
            sep25:[{name:[],place:[]}],
            sep26:[{name:[],place:[]}],
            sep27:[{name:[],place:[]}],
            sep28:[{name:[],place:[]}],
            sep29:[{name:[],place:[]}],
            sep30:[{name:[],place:[]}],
            sep31:[{name:[],place:[]}],

            // October ------------------------------------------------------------

            oct1:[{name:[],place:[]}],
            oct2:[{name:[],place:[]}],
            oct3:[{name:[],place:[]}],
            oct4:[{name:[],place:[]}],
            oct5:[{name:[],place:[]}],
            oct6:[{name:[],place:[]}],
            oct7:[{name:[],place:[]}],
            oct8:[{name:[],place:[]}],
            oct9:[{name:[],place:[]}],
            oct10:[{name:[],place:[]}],
            oct11:[{name:[],place:[]}],
            oct12:[{name:[],place:[]}],
            oct13:[{name:[],place:[]}],
            oct14:[{name:[],place:[]}],
            oct15:[{name:[],place:[]}],
            oct16:[{name:[],place:[]}],
            oct17:[{name:[],place:[]}],
            oct18:[{name:[],place:[]}],
            oct19:[{name:[],place:[]}],
            oct20:[{name:[],place:[]}],
            oct21:[{name:[],place:[]}],
            oct22:[{name:[],place:[]}],
            oct23:[{name:[],place:[]}],
            oct24:[{name:[],place:[]}],
            oct25:[{name:[],place:[]}],
            oct26:[{name:[],place:[]}],
            oct27:[{name:["SREEJA SREEJESH"],place:["KUTHUPARAMBA"]}],
            oct28:[{name:[],place:[]}],
            oct29:[{name:[],place:[]}],
            oct30:[{name:[],place:[]}],
            oct31:[{name:[],place:[]}],

            // November ---------------------------------------------------

            nov1:[{name:[],place:[]}],
            nov2:[{name:["MINI RAJU"],place:["NEDUVALOOR"]}],
            nov3:[{name:[],place:[]}],
            nov4:[{name:[],place:[]}],
            nov5:[{name:[],place:[]}],
            nov6:[{name:[],place:[]}],
            nov7:[{name:[],place:[]}],
            nov8:[{name:[],place:[]}],
            nov9:[{name:[],place:[]}],
            nov10:[{name:[],place:[]}],
            nov11:[{name:[],place:[]}],
            nov12:[{name:[],place:[]}],
            nov13:[{name:[],place:[]}],
            nov14:[{name:["LEELAMMA THOMAS"],place:["ANAPANTHI"]}],
            nov15:[{name:[],place:[]}],
            nov16:[{name:[],place:[]}],
            nov17:[{name:[],place:[]}],
            nov18:[{name:[],place:[]}],
            nov19:[{name:[],place:[]}],
            nov20:[{name:[],place:[]}],
            nov21:[{name:[],place:['kannur']}],
            nov22:[{name:['HELLO'],place:[]}],
            nov23:[{name:[],place:[]}],
            nov24:[{name:["REENA SHIRLY"],place:["KULAPPURAM"]}],
            nov25:[{name:[],place:[]}],
            nov26:[{name:[],place:[]}],
            nov27:[{name:[],place:[]}],
            nov28:[{name:[],place:[]}],
            nov29:[{name:[],place:[]}],
            nov30:[{name:[],place:[]}],
            nov31:[{name:[],place:[]}],

            // December ------------------------------------------------------------------

            dec1:[{name:[],place:[]}],
            dec2:[{name:[],place:[]}],
            dec3:[{name:[],place:[]}],
            dec4:[{name:["SHINY CHACKO"],place:["PARAKKAPPARA"]}],
            dec5:[{name:[],place:[]}],
            dec6:[{name:[],place:[]}],
            dec7:[{name:[],place:[]}],
            dec8:[{name:[],place:[]}],
            dec9:[{name:[],place:[]}],
            dec10:[{name:[],place:[]}],
            dec11:[{name:[],place:[]}],
            dec12:[{name:["SHINI ANIL"],place:["MATTUL"]}],
            dec13:[{name:[],place:[]}],
            dec14:[{name:[],place:[]}],
            dec15:[{name:[],place:[]}],
            dec16:[{name:[],place:[]}],
            dec17:[{name:[],place:[]}],
            dec18:[{name:[],place:[]}],
            dec19:[{name:[],place:[]}],
            dec20:[{name:[],place:[]}],
            dec21:[{name:[],place:[]}],
            dec22:[{name:[],place:[]}],
            dec23:[{name:[],place:[]}],
            dec24:[{name:[],place:[]}],
            dec25:[{name:[],place:[]}],
            dec26:[{name:[],place:[]}],
            dec27:[{name:["BINCY REJI"],place:["IRITTY"]}],
            dec28:[{name:[],place:[]}],
            dec29:[{name:[],place:[]}],
            dec30:[{name:[],place:[]}],
            dec31:[{name:[],place:[]}],
        }



