module.exports = {
  // January
  jan1: [{ name: [], image: [] }],
  jan2: [{ name: [], image: [] }],
  jan3: [{ name: [], image: [] }],
  jan4: [{ name: [], image: [] }],
  jan5: [{ name: [], image: [] }],
  jan6: [{ name: [], image: [] }],
  jan7: [{ name: [], image: [] }],
  jan8: [{ name: [], image: [] }],
  jan9: [{ name: [], image: [] }],
  jan10: [{ name: [], image: [] }],
  jan11: [{ name: [], image: [] }],
  jan12: [{ name: [], image: [] }],
  jan13: [{ name: [], image: [] }],
  jan14: [{ name: [], image: [] }],
  jan15: [{ name: [], image: [] }],
  jan16: [{ name: [], image: [] }],
  jan17: [{ name: [], image: [] }],
  jan18: [{ name: [], image: [] }],
  jan19: [{ name: [], image: [] }],
  jan20: [{ name: [], image: [] }],
  jan21: [{ name: [], image: [] }],
  jan22: [{ name: [], image: [] }],
  jan23: [{ name: [], image: [] }],
  jan24: [{ name: [], image: [] }],
  jan25: [{ name: [], image: [] }],
  jan26: [{ name: [], image: [] }],
  jan27: [{ name: [], image: [] }],
  jan28: [{ name: [], image: [] }],
  jan29: [{ name: [], image: [] }],
  jan30: [{ name: [], image: [] }],
  jan31: [{ name: [], image: [] }],

  // February

  feb1: [{ name: [], image: [] }],
  feb2: [{ name: [], image: [] }],
  feb3: [{ name: [], image: [] }],
  feb4: [{ name: [], image: [] }],
  feb5: [{ name: [], image: [] }],
  feb6: [{ name: [], image: [] }],
  feb7: [{ name: [], image: [] }],
  feb8: [{ name: ['REV. ROBERT JOHN & LISSY ROBERT'], image: ['https://drive.google.com/uc?export=view&id=12zxN6-Gmnef-gn8X-wZAL6SaJkhSBI-A'] }],
  feb9: [{ name: [], image: [] }],
  feb10: [{ name: [], image: [] }],
  feb11: [{ name: [], image: [] }],
  feb12: [{ name: [], image: [] }],
  feb13: [{ name: [], image: [] }],
  feb14: [{ name: [], image: [] }],
  feb15: [{ name: [], image: [] }],
  feb16: [{ name: [], image: [] }],
  feb17: [{ name: [], image: [] }],
  feb18: [{ name: [], image: [] }],
  feb19: [{ name: ['REV. T J JOSEPH & JISHA JOSEPH'], image: ['https://drive.google.com/uc?export=view&id=1Yc05vpYrwXLmf5GRM7aZyeacucKkEB00'] }],
  feb20: [{ name: [], image: [] }],
  feb21: [{ name: [], image: [] }],
  feb22: [{ name: [], image: [] }],
  feb23: [{ name: [], image: [] }],
  feb24: [{ name: [], image: [] }],
  feb25: [{ name: [], image: [] }],
  feb26: [{ name: [], image: [] }],
  feb27: [{ name: [], image: [] }],
  feb28: [{ name: [], image: [] }],
  feb29: [{ name: [], image: [] }],

  // March

  mar1: [{ name: [], image: [] }],
  mar2: [{ name: [], image: [] }],
  mar3: [{ name: [], image: [] }],
  mar4: [{ name: [], image: [] }],
  mar5: [{ name: [], image: [] }],
  mar6: [{ name: [], image: [] }],
  mar7: [{ name: [], image: [] }],
  mar8: [{ name: [], image: [] }],
  mar9: [{ name: [], image: [] }],
  mar10: [{ name: [], image: [] }],
  mar11: [{ name: [], image: [] }],
  mar12: [{ name: [], image: [] }],
  mar13: [{ name: [], image: [] }],
  mar14: [{ name: [], image: [] }],
  mar15: [{ name: [], image: [] }],
  mar16: [{ name: [], image: [] }],
  mar17: [{ name: [], image: [] }],
  mar18: [{ name: [], image: [] }],
  mar19: [{ name: [], image: [] }],
  mar20: [{ name: [], image: [] }],
  mar21: [{ name: [], image: [] }],
  mar22: [{ name: [], image: [] }],
  mar23: [{ name: [], image: [] }],
  mar24: [{ name: [], image: [] }],
  mar25: [{ name: [], image: [] }],
  mar26: [{ name: [], image: [] }],
  mar27: [{ name: [], image: [] }],
  mar28: [{ name: [], image: [] }],
  mar29: [{ name: [], image: [] }],
  mar30: [{ name: [], image: [] }],
  mar31: [{ name: [], image: [] }],

  // April

  apr1: [{ name: [], image: [] }],
  apr2: [{ name: [], image: [] }],
  apr3: [{ name: [], image: [] }],
  apr4: [{ name: [], image: [] }],
  apr5: [{ name: [], image: [] }],
  apr6: [{ name: [], image: [] }],
  apr7: [{ name: [], image: [] }],
  apr8: [{ name: [], image: [] }],
  apr9: [{ name: [], image: [] }],
  apr10: [{ name: [], image: [] }],
  apr11: [{ name: [], image: [] }],
  apr12: [{ name: [], image: [] }],
  apr13: [{ name: [], image: [] }],
  apr14: [{ name: [], image: [] }],
  apr15: [{ name: [], image: [] }],
  apr16: [{ name: ['EVG. N C MATHEW & LALI MATHEW'], image: ['https://drive.google.com/uc?export=view&id=14yXNZYAe4s_p0_wOWOjdLUZzyzxl72ax'] }],
  apr17: [{ name: ['EVG. SAM THOMAS & LIJI SAM'], image: ['https://drive.google.com/uc?export=view&id=1ZgGzfxqj7hgbd4URfTfCcvI5oNuxPMgu'] }],
  apr18: [{ name: [], image: [] }],
  apr19: [{ name: [], image: [] }],
  apr20: [{ name: [], image: [] }],
  apr21: [{ name: [], image: [] }],
  apr22: [{ name: [], image: [] }],
  apr23: [{ name: [], image: [] }],
  apr24: [{ name: [], image: [] }],
  apr25: [{ name: [], image: [] }],
  apr26: [{ name: [], image: [] }],
  apr27: [{ name: ['REV. JOY ALEX & PRAVEENA JOY'], image: ['https://drive.google.com/uc?export=view&id=1eMAEhfEzcZ4xi4moM-rvWf0EfyqghlOQ'] }],
  apr28: [{ name: ['EVG. K V THOMAS & LEELAMMA THOMAS'], image: ['https://drive.google.com/uc?export=view&id=1S-jRAN-2mFMB3kuAjaEg8Bket043Ll-v'] }],
  apr29: [{ name: [], image: [] }],
  apr30: [{ name: [], image: [] }],

  // May

  may1: [{ name: [], image: [] }],
  may2: [{ name: [], image: [] }],
  may3: [{ name: [], image: [] }],
  may4: [{ name: ['REV. RAJU CHEERAN & LINTA RAJU CHEERAN'], image: ['https://drive.google.com/uc?export=view&id=1vpmZxBANQ5hQiYFCxHL29YRqO7y0peCA'] }],
  may5: [{ name: [], image: [] }],
  may6: [{ name: [], image: [] }],
  may7: [{ name: [], image: [] }],
  may8: [{ name: [], image: [] }],
  may9: [{ name: [], image: [] }],
  may10: [{ name: [], image: [] }],
  may11: [{ name: [], image: [] }],
  may12: [{ name: [], image: [] }],
  may13: [{ name: [], image: [] }],
  may14: [{ name: [], image: [] }],
  may15: [{ name: [], image: [] }],
  may16: [{ name: [], image: [] }],
  may17: [{ name: [], image: [] }],
  may18: [{ name: [], image: [] }],
  may19: [{ name: [], image: [] }],
  may20: [{ name: [], image: [] }],
  may21: [{ name: ['REV. REJI THOMAS & BINCY REJI'], image: ['https://drive.google.com/uc?export=view&id=1-5mBmPwbutKKus0PhD0AgmkIfUwc_YW4'] }],
  may22: [{ name: [], image: [] }],
  may23: [{ name: [], image: [] }],
  may24: [{ name: [], image: [] }],
  may25: [{ name: [], image: [] }],
  may26: [{ name: [], image: [] }],
  may27: [{ name: [], image: [] }],
  may28: [{ name: [], image: [] }],
  may29: [{ name: [], image: [] }],
  may30: [{ name: [], image: [] }],
  may31: [{ name: [], image: [] }],

  // June

  jun1: [{ name: [], image: [] }],
  jun2: [{ name: [], image: [] }],
  jun3: [{ name: [], image: [] }],
  jun4: [{ name: [], image: [] }],
  jun5: [{ name: [], image: [] }],
  jun6: [{ name: [], image: [] }],
  jun7: [{ name: ['EVG. V M RAJU & MINI RAJU'], image: ['https://drive.google.com/uc?export=view&id=1rm4ZRlNGGyUqtfJco6hU9opVMrLT5w0k'] }],
  jun8: [{ name: [], image: [] }],
  jun9: [{ name: [], image: [] }],
  jun10: [{ name: ['EVG. E K CHRISPUS & ANNAMMA CHRISPUS'], image: ['https://drive.google.com/uc?export=view&id=1VbQKSe8BABbZNW82PZNdHKXHDrd3McJ5'] }],
  jun11: [{ name: [], image: [] }],
  jun12: [{ name: [], image: [] }],
  jun13: [{ name: [], image: [] }],
  jun14: [{ name: [], image: [] }],
  jun15: [{ name: [], image: [] }],
  jun16: [{ name: ['REV. SATHYA GEORGE & VALSAMMA GEORGE'], image: ['https://drive.google.com/uc?export=view&id=13suHsgscyrHmdVz9FSYDhvPWk92IMHSA'] }],
  jun17: [{ name: [], image: [] }],
  jun18: [{ name: [], image: [] }],
  jun19: [{ name: [], image: [] }],
  jun20: [{ name: [], image: [] }],
  jun21: [{ name: [], image: [] }],
  jun22: [{ name: [], image: [] }],
  jun23: [{ name: [], image: [] }],
  jun24: [{ name: [], image: [] }],
  jun25: [{ name: [], image: [] }],
  jun26: [{ name: [], image: [] }],
  jun27: [{ name: [], image: [] }],
  jun28: [{ name: [], image: [] }],
  jun29: [{ name: [], image: [] }],
  jun30: [{ name: [], image: [] }],

  // July

  jul1: [{ name: [], image: [] }],
  jul2: [{ name: ['EVG. M M RAJU & JESSY RAJU'], image: ['https://drive.google.com/uc?export=view&id=1tAoMx87KEV9zQH7UP8kZJF4YQ-jyCfB2'] }],
  jul3: [{ name: [], image: [] }],
  jul4: [{ name: [], image: [] }],
  jul5: [{ name: [], image: [] }],
  jul6: [{ name: [], image: [] }],
  jul7: [{ name: ['Rev James Mathew & Smitha James'], image: ['https://drive.google.com/uc?export=view&id=1j8VWORyH0kNQvRgyCeCuyewGS5KPAtVU'] }],
  jul8: [{ name: [], image: [] }],
  jul9: [{ name: [], image: [] }],
  jul10: [{ name: [], image: [] }],
  jul11: [{ name: [], image: [] }],
  jul12: [{ name: [], image: [] }],
  jul13: [{ name: [], image: [] }],
  jul14: [{ name: [], image: [] }],
  jul15: [{ name: [], image: [] }],
  jul16: [{ name: [], image: [] }],
  jul17: [{ name: [], image: [] }],
  jul18: [{ name: [], image: [] }],
  jul19: [{ name: [], image: [] }],
  jul20: [{ name: [], image: [] }],
  jul21: [{ name: [], image: [] }],
  jul22: [{ name: [], image: [] }],
  jul23: [{ name: [], image: [] }],
  jul24: [{ name: [], image: [] }],
  jul25: [{ name: [], image: [] }],
  jul26: [{ name: [], image: [] }],
  jul27: [{ name: [], image: [] }],
  jul28: [{ name: [], image: [] }],
  jul29: [{ name: [], image: [] }],
  jul30: [{ name: [], image: [] }],
  jul31: [{ name: [], image: [] }],

  // August

  aug1: [{ name: [], image: [] }],
  aug2: [{ name: [], image: [] }],
  aug3: [{ name: [], image: [] }],
  aug4: [{ name: [], image: [] }],
  aug5: [{ name: [], image: [] }],
  aug6: [{ name: [], image: [] }],
  aug7: [{ name: [], image: [] }],
  aug8: [{ name: [], image: [] }],
  aug9: [{ name: [], image: [] }],
  aug10: [{ name: [], image: [] }],
  aug11: [{ name: [], image: [] }],
  aug12: [{ name: [], image: [] }],
  aug13: [{ name: [], image: [] }],
  aug14: [{ name: [], image: [] }],
  aug15: [{ name: [], image: [] }],
  aug16: [{ name: [], image: [] }],
  aug17: [{ name: ['REV. JOBI GEORGE & LIZ JOSEPHINE GEORGE'], image: ['https://drive.google.com/uc?export=view&id=1lbMjq6OcWU_-qb_3GbZRkiaUcuSsbbg1'] }],
  aug18: [{ name: [], image: [] }],
  aug19: [{ name: [], image: [] }],
  aug20: [{ name: [], image: [] }],
  aug21: [{ name: [], image: [] }],
  aug22: [{ name: [], image: [] }],
  aug23: [{ name: [], image: [] }],
  aug24: [{ name: [], image: [] }],
  aug25: [{ name: [], image: [] }],
  aug26: [{ name: [], image: [] }],
  aug27: [{ name: [], image: [] }],
  aug28: [{ name: [], image: [] }],
  aug29: [{ name: ['REV. DN. SUJITH JOSEPH & CHISTEENA SUJITH'], image: ['https://drive.google.com/uc?export=view&id=1Vc2rXHF2X3L2KOqNAxstf3LVHzDN0kuO'] }],
  aug30: [{ name: [], image: [] }],
  aug31: [{ name: [], image: [] }],

  // September

  sep1: [{ name: [], image: [] }],
  sep2: [{ name: [], image: [] }],
  sep3: [{ name: [], image: [] }],
  sep4: [{ name: [], image: [] }],
  sep5: [{ name: [], image: [] }],
  sep6: [{ name: [], image: [] }],
  sep7: [{ name: [], image: [] }],
  sep8: [{ name: [], image: [] }],
  sep9: [{ name: [], image: [] }],
  sep10: [{ name: [], image: [] }],
  sep11: [{ name: ['EVG. BINOY LAMBERT & REMYA BINOY'], image: ['https://drive.google.com/uc?export=view&id=1zBo4MdwATm5PFYeGJO9zHSc_Qmjq-7_c'] }],
  sep12: [{ name: [], image: [] }],
  sep13: [{ name: [], image: [] }],
  sep14: [{ name: [], image: [] }],
  sep15: [{ name: [], image: [] }],
  sep16: [{ name: [], image: [] }],
  sep17: [{ name: ['REV. BABU DAYANANDAN & SAJITHA MARIAM PHILIP'], image: ['https://drive.google.com/uc?export=view&id=15mqibB8TIKao2-soflrISXQ5lIbvkjqJ'] }],
  sep18: [{ name: [], image: [] }],
  sep19: [{ name: [], image: [] }],
  sep20: [{ name: [], image: [] }],
  sep21: [{ name: ['REV. JIJO ALBERT & NEETHU JIJO'], image: ['https://drive.google.com/uc?export=view&id=1EMAHAbXiHd-4O1U3iWWEFf1gdptL2zXG'] }],
  sep22: [{ name: [], image: [] }],
  sep23: [{ name: [], image: [] }],
  sep24: [{ name: [], image: [] }],
  sep25: [{ name: [], image: [] }],
  sep26: [{ name: [], image: [] }],
  sep27: [{ name: [], image: [] }],
  sep28: [{ name: [], image: [] }],
  sep29: [{ name: [], image: [] }],
  sep30: [{ name: [], image: [] }],

  // October

  oct1: [{ name: [], image: [] }],
  oct2: [{ name: [], image: [] }],
  oct3: [{ name: [], image: [] }],
  oct4: [{ name: [], image: [] }],
  oct5: [{ name: [], image: [] }],
  oct6: [{ name: [], image: [] }],
  oct7: [{ name: [], image: [] }],
  oct8: [{ name: [], image: [] }],
  oct9: [{ name: [], image: [] }],
  oct10: [{ name: [], image: [] }],
  oct11: [{ name: [], image: [] }],
  oct12: [{ name: [], image: [] }],
  oct13: [{ name: [], image: [] }],
  oct14: [{ name: [], image: [] }],
  oct15: [{ name: [], image: [] }],
  oct16: [{ name: [], image: [] }],
  oct17: [{ name: [], image: [] }],
  oct18: [{ name: [], image: [] }],
  oct19: [{ name: [], image: [] }],
  oct20: [{ name: [], image: [] }],
  oct21: [{ name: [], image: [] }],
  oct22: [{ name: [], image: [] }],
  oct23: [{ name: [], image: [] }],
  oct24: [{ name: [], image: [] }],
  oct25: [{ name: [], image: [] }],
  oct26: [{ name: [], image: [] }],
  oct27: [{ name: [], image: [] }],
  oct28: [{ name: ['EVG. BENJAMIN MATHEW & SULOCHANA BENJAMIN'], image: ['https://drive.google.com/uc?export=view&id=1au_HC44uT4Sx9BwNiGZ0QEZ8qWjFGs2y'] }],
  oct29: [{ name: [], image: [] }],
  oct30: [{ name: [], image: [] }],
  oct31: [{ name: [], image: [] }],

  // November

  nov1: [{ name: [], image: [] }],
  nov2: [{ name: [], image: [] }],
  nov3: [{ name: [], image: [] }],
  nov4: [{ name: [], image: [] }],
  nov5: [{ name: [], image: [] }],
  nov6: [{ name: [], image: [] }],
  nov7: [{ name: [], image: [] }],
  nov8: [{ name: [], image: [] }],
  nov9: [{ name: [], image: [] }],
  nov10: [{ name: [], image: [] }],
  nov11: [{ name: [], image: [] }],
  nov12: [{ name: [], image: [] }],
  nov13: [{ name: [], image: [] }],
  nov14: [{ name: [], image: [] }],
  nov15: [{ name: [], image: [] }],
  nov16: [{ name: [], image: [] }],
  nov17: [{ name: [], image: [] }],
  nov18: [{ name: [], image: [] }],
  nov19: [{ name: [], image: [] }],
  nov20: [{ name: [], image: [] }],
  nov21: [{ name: [], image: [] }],
  nov22: [{ name: [], image: [] }],
  nov23: [{ name: [], image: [] }],
  nov24: [{ name: [], image: [] }],
  nov25: [{ name: [], image: [] }],
  nov26: [{ name: [], image: [] }],
  nov27: [{ name: [], image: [] }],
  nov28: [{ name: ['REV. TREVOR JYOTISH W & ANNE TREVOR'], image: ['https://drive.google.com/uc?export=view&id=1T336xCYum8amNL1JA4eLvE7DsxWpDfh-'] }],
  nov29: [{ name: [], image: [] }],
  nov30: [{ name: [], image: [] }],

  // December

  dec1: [{ name: [], image: [] }],
  dec2: [{ name: [], image: [] }],
  dec3: [{ name: [], image: [] }],
  dec4: [{ name: [], image: [] }],
  dec5: [{ name: [], image: [] }],
  dec6: [{ name: [], image: [] }],
  dec7: [{ name: [], image: [] }],
  dec8: [{ name: [], image: [] }],
  dec9: [{ name: [], image: [] }],
  dec10: [{ name: [], image: [] }],
  dec11: [{ name: [], image: [] }],
  dec12: [{ name: [], image: [] }],
  dec13: [{ name: [], image: [] }],
  dec14: [{ name: [], image: [] }],
  dec15: [{ name: [], image: [] }],
  dec16: [{ name: [], image: [] }],
  dec17: [{ name: [], image: [] }],
  dec18: [{ name: [], image: [] }],
  dec19: [{ name: [], image: [] }],
  dec20: [{ name: [], image: [] }],
  dec21: [{ name: [], image: [] }],
  dec22: [{ name: [], image: [] }],
  dec23: [{ name: [], image: [] }],
  dec24: [{ name: [], image: [] }],
  dec25: [{ name: [], image: [] }],
  dec26: [{ name: [], image: [] }],
  dec27: [{ name: [], image: [] }],
  dec28: [{ name: [], image: [] }],
  dec29: [{ name: [], image: [] }],
  dec30: [{ name: [], image: [] }],
  dec31: [{ name: [], image: [] }],
}
